# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v2
  
    - run: yarn install
    - run: yarn run test
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
            push: true
            tags:  ${{ secrets.DOCKER_USER }}/app:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
